# Generated by Django 3.2.16 on 2022-11-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mood',
            field=models.IntegerField(null=True),
        ),
    ]
